apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: service-catalog-monitor
  labels:
    release: kube-prom-stack
spec:
  selector:
    matchLabels:
      app: service-catalog
  namespaceSelector:
    matchNames:
      - developer-portal
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: service-identity-monitor
  labels:
    release: kube-prom-stack
spec:
  selector:
    matchLabels:
      app: service-identity
  namespaceSelector:
    matchNames:
      - developer-portal
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
