apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: developer-portal

resources:
  - namespace.yaml
  - postgres/postgres-secret.yaml
  - postgres/postgres-pvc.yaml
  - postgres/postgres.yaml
  - backstage/backstage-configmap.yaml
  - backstage/backstage-secret.yaml
  - backstage/backstage-backend.yaml
  - backstage/backstage-frontend.yaml
  - backstage/ingress.yaml
  - backstage/ingress-public.yaml
  - services/service-catalog.yaml
  - services/service-identity.yaml
  - rbac/backstage-rbac.yaml
  - monitoring/service-monitors.yaml
