apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - target:
      kind: ConfigMap
      name: backstage-config
    patch: |-
      - op: replace
        path: /data/BACKSTAGE_BASE_URL
        value: http://portal.local
      - op: replace
        path: /data/BACKEND_BASE_URL
        value: http://portal.local/api
